# Pandas Assignment

In [1]:
import pandas as pd
import numpy as np

### Read the CSV file "Flights_20200601_20200630.csv.gz" as **flights**  (1pt)

In [2]:
# flights = pd.read_...
flights = pd.read_csv("Flights_20200601_20200630.csv.gz", parse_dates=True)

### View rows at the start of the data frame (1pt)

In [3]:
flights.head()

,ECTRL ID,ADEP,ADEP Latitude,ADEP Longitude,ADES,ADES Latitude,ADES Longitude,FILED OFF BLOCK TIME,FILED ARRIVAL TIME,ACTUAL OFF BLOCK TIME,ACTUAL ARRIVAL TIME,AC Type,AC Operator,AC Registration,ICAO Flight Type,STATFOR Market Segment,Requested FL,Actual Distance Flown (nm)
0,239675736,MMLP,24.08333,-110.36667,EGSS,51.88500,0.23500,01-06-2020 00:00:00,01-06-2020 10:59:59,01-06-2020 00:19:07,01-06-2020 10:53:56,GLF5,ZZZ,N194MF,N,Business Aviation,450.0,5140
1,239675737,ZUCK,29.72000,106.64000,EHAM,52.30806,4.76417,01-06-2020 00:00:00,01-06-2020 10:34:31,01-06-2020 00:24:00,01-06-2020 11:19:14,A333,CSN,B300U,N,Charter,380.0,4460
2,239675738,ZSPD,31.13333,121.78333,EHAM,52.30806,4.76417,01-06-2020 00:00:00,01-06-2020 11:38:08,01-06-2020 00:16:00,01-06-2020 12:32:50,A333,CSN,B1063,N,Charter,361.0,4843
3,239675739,UUDD,55.40861,37.90639,EBLG,50.63639,5.44278,01-06-2020 00:00:00,01-06-2020 02:45:51,31-05-2020 23:55:00,01-06-2020 02:49:07,B748,ABW,VQBFE,N,All-Cargo,340.0,1246
4,239675740,KEWR,40.69667,-74.16833,LLBG,32.00944,34.88556,01-06-2020 00:00:00,01-06-2020 10:14:05,01-06-2020 00:12:00,01-06-2020 10:28:18,B78X,UAL,N17002,S,Mainline,310.0,5076

### View rows at the end of the data frame (1pt)

In [4]:
flights.tail()

,ECTRL ID,ADEP,ADEP Latitude,ADEP Longitude,ADES,ADES Latitude,ADES Longitude,FILED OFF BLOCK TIME,FILED ARRIVAL TIME,ACTUAL OFF BLOCK TIME,ACTUAL ARRIVAL TIME,AC Type,AC Operator,AC Registration,ICAO Flight Type,STATFOR Market Segment,Requested FL,Actual Distance Flown (nm)
164161,239892812,OAMS,36.70000,67.10000,EDDK,50.86583,7.14278,30-06-2020 23:55:00,01-07-2020 06:59:24,30-06-2020 23:46:38,01-07-2020 07:00:09,B763,PVG,ECLZO,N,Charter,320.0,2834
164162,239893933,DAAG,36.69444,3.21694,EDDK,50.86583,7.14278,30-06-2020 23:55:00,01-07-2020 02:17:30,30-06-2020 23:40:46,01-07-2020 02:04:20,A321,ART,YLLDA,N,Charter,330.0,957
164163,239894479,UKBB,50.34472,30.89333,LTAC,40.12806,32.99500,30-06-2020 23:55:00,01-07-2020 02:01:58,30-06-2020 23:50:00,01-07-2020 01:33:00,B738,PGT,TCCRA,S,Lowcost,370.0,659
164164,239896814,EGSS,51.88500,0.23500,EGPH,55.95000,-3.37250,30-06-2020 23:55:00,01-07-2020 01:02:00,30-06-2020 23:41:00,01-07-2020 00:46:22,B734,NPT,GCKUZ,S,All-Cargo,340.0,296
164165,239895061,EDDP,51.42389,12.23639,LTBA,40.97611,28.81417,30-06-2020 23:58:00,01-07-2020 02:28:04,30-06-2020 23:54:00,01-07-2020 02:20:00,A306,MNB,TCMCD,S,All-Cargo,350.0,975

### View random 10 rows (1pt)

In [5]:
flights.sample(10)

,ECTRL ID,ADEP,ADEP Latitude,ADEP Longitude,ADES,ADES Latitude,ADES Longitude,FILED OFF BLOCK TIME,FILED ARRIVAL TIME,ACTUAL OFF BLOCK TIME,ACTUAL ARRIVAL TIME,AC Type,AC Operator,AC Registration,ICAO Flight Type,STATFOR Market Segment,Requested FL,Actual Distance Flown (nm)
58740,239756372,UBBB,40.46972,50.05139,EDDP,51.42389,12.23639,13-06-2020 23:15:00,14-06-2020 04:10:47,13-06-2020 23:37:00,14-06-2020 04:15:58,IL76,AZQ,4KAZ101,N,All-Cargo,340.0,1828
16495,239699206,LIEO,40.89861,9.51778,LIMC,45.63000,8.72306,04-06-2020 16:40:00,04-06-2020 17:49:56,04-06-2020 16:26:00,04-06-2020 17:31:43,A320,AZA,EIDTH,S,Mainline,300.0,332
66764,239767008,EBBR,50.90139,4.48444,EKCH,55.61806,12.65611,15-06-2020 13:55:00,15-06-2020 15:17:18,15-06-2020 13:54:00,15-06-2020 15:13:37,A319,BEL,OOSSJ,S,Mainline,370.0,440
100470,239812165,LTFH,41.26556,36.54861,LTFJ,40.89833,29.30917,21-06-2020 11:45:00,21-06-2020 13:13:26,21-06-2020 11:52:00,21-06-2020 13:14:00,B738,THY,TCJFO,S,Mainline,340.0,488
47344,239741096,EGLL,51.47750,-0.46139,KATL,33.63333,-84.43333,11-06-2020 11:50:00,11-06-2020 20:40:57,11-06-2020 11:40:00,11-06-2020 20:33:16,A333,DAL,N808NW,S,Mainline,360.0,3786
25440,239711087,LPFR,37.01444,-7.96583,LFMN,43.66528,7.21500,06-06-2020 16:30:00,06-06-2020 18:35:34,06-06-2020 16:14:00,06-06-2020 18:16:50,C56X,AHO,DCGAA,N,Business Aviation,400.0,849
111654,239826472,ENAL,62.56250,6.11972,ENGM,60.20278,11.08389,23-06-2020 06:25:00,23-06-2020 07:18:54,23-06-2020 06:15:00,23-06-2020 07:05:23,B738,SAS,LNRPM,S,Mainline,350.0,222
63006,239761636,UNNT,55.01167,82.65167,ELLX,49.62333,6.20444,14-06-2020 23:35:00,15-06-2020 05:35:51,14-06-2020 23:34:00,15-06-2020 05:40:46,B744,CLX,LXRCV,S,All-Cargo,340.0,2704
23833,239708868,LIMJ,44.41333,8.83750,LEMG,36.67500,-4.49917,06-06-2020 08:45:00,06-06-2020 12:40:38,06-06-2020 08:46:00,06-06-2020 12:29:38,BE20,ZZZ,DCEER,N,Business Aviation,300.0,805
101544,239813526,LTFJ,40.89833,29.30917,LTAU,38.77028,35.49528,21-06-2020 14:30:00,21-06-2020 15:36:10,21-06-2020 14:28:00,21-06-2020 15:34:10,A320,PGT,TCDCM,S,Lowcost,350.0,352

In [6]:
# follow code will rename the column names and convert datetime columns

flights = (
    flights.rename(
        columns={
            "FILED OFF BLOCK TIME": "fobt",
            "FILED ARRIVAL TIME": "fat",
            "ACTUAL OFF BLOCK TIME": "aobt",
            "ACTUAL ARRIVAL TIME": "aat",
            "STATFOR Market Segment": "market",
            "ADEP": "origin",
            "ADES": "destination",
            "ADEP Latitude": "lat_orig",
            "ADEP Longitude": "lon_orig",
            "ADES Latitude": "lat_dest",
            "ADES Longitude": "lon_dest",
            "AC Type": "actype",
            "AC Operator": "operator",
            "AC Registration": "reg",
            "ICAO Flight Type": "flighttype",
            "ECTRL ID": "id",
            "Requested FL": "requestfl",
            "Actual Distance Flown (nm)": "distance",
        }
    )
    .assign(fobt=lambda d: pd.to_datetime(d.fobt, format="%d-%m-%Y %H:%M:%S", utc=True))
    .assign(aobt=lambda d: pd.to_datetime(d.aobt, format="%d-%m-%Y %H:%M:%S", utc=True))
    .assign(fat=lambda d: pd.to_datetime(d.fat, format="%d-%m-%Y %H:%M:%S", utc=True))
    .assign(aat=lambda d: pd.to_datetime(d.aat, format="%d-%m-%Y %H:%M:%S", utc=True))
)

### Save the file to parquet file and read it back again (1pt)

In [ ]:
par_name = 'flights_parq.parquet'
flights.to_parquet(par_name)

flights = pd.read_parquet(par_name)

### Query flights with aircraft type A388 (Airbus A380-800) (1pt)

In [7]:
flights.head()

,id,origin,lat_orig,lon_orig,destination,lat_dest,lon_dest,fobt,fat,aobt,aat,actype,operator,reg,flighttype,market,requestfl,distance
0,239675736,MMLP,24.08333,-110.36667,EGSS,51.88500,0.23500,2020-06-01 00:00:00+00:00,2020-06-01 10:59:59+00:00,2020-06-01 00:19:07+00:00,2020-06-01 10:53:56+00:00,GLF5,ZZZ,N194MF,N,Business Aviation,450.0,5140
1,239675737,ZUCK,29.72000,106.64000,EHAM,52.30806,4.76417,2020-06-01 00:00:00+00:00,2020-06-01 10:34:31+00:00,2020-06-01 00:24:00+00:00,2020-06-01 11:19:14+00:00,A333,CSN,B300U,N,Charter,380.0,4460
2,239675738,ZSPD,31.13333,121.78333,EHAM,52.30806,4.76417,2020-06-01 00:00:00+00:00,2020-06-01 11:38:08+00:00,2020-06-01 00:16:00+00:00,2020-06-01 12:32:50+00:00,A333,CSN,B1063,N,Charter,361.0,4843
3,239675739,UUDD,55.40861,37.90639,EBLG,50.63639,5.44278,2020-06-01 00:00:00+00:00,2020-06-01 02:45:51+00:00,2020-05-31 23:55:00+00:00,2020-06-01 02:49:07+00:00,B748,ABW,VQBFE,N,All-Cargo,340.0,1246
4,239675740,KEWR,40.69667,-74.16833,LLBG,32.00944,34.88556,2020-06-01 00:00:00+00:00,2020-06-01 10:14:05+00:00,2020-06-01 00:12:00+00:00,2020-06-01 10:28:18+00:00,B78X,UAL,N17002,S,Mainline,310.0,5076

In [8]:
flights.query("actype == 'A388'")

,id,origin,lat_orig,lon_orig,destination,lat_dest,lon_dest,fobt,fat,aobt,aat,actype,operator,reg,flighttype,market,requestfl,distance
1495,239677853,FAOR,NaN,NaN,EGLL,51.47750,-0.46139,2020-06-01 10:05:00+00:00,2020-06-01 21:15:07+00:00,2020-06-01 10:13:23+00:00,2020-06-01 21:22:59+00:00,A388,BAW,GXLEG,N,Charter,360.0,5005
8116,239687159,ZGGG,23.39333,113.30833,EGLL,51.47750,-0.46139,2020-06-03 01:30:00+00:00,2020-06-03 13:15:00+00:00,2020-06-03 01:36:00+00:00,2020-06-03 13:33:05+00:00,A388,CSN,B6139,S,Mainline,361.0,5227
11480,239692225,ZGGG,23.39333,113.30833,EHAM,52.30806,4.76417,2020-06-03 16:05:00+00:00,2020-06-04 03:26:33+00:00,2020-06-03 16:09:00+00:00,2020-06-04 03:40:36+00:00,A388,CSN,B6138,S,Mainline,381.0,5044
14739,239696598,FAOR,NaN,NaN,EGLL,51.47750,-0.46139,2020-06-04 10:05:00+00:00,2020-06-04 21:08:24+00:00,2020-06-04 10:08:06+00:00,2020-06-04 21:07:54+00:00,A388,BAW,GXLEG,N,Charter,380.0,4965
17462,239700336,EGLL,51.47750,-0.46139,ZGGG,23.39333,113.30833,2020-06-04 21:35:00+00:00,2020-06-05 08:35:15+00:00,2020-06-04 21:35:00+00:00,2020-06-05 08:32:02+00:00,A388,CSN,B6139,S,Mainline,330.0,5225
20153,239704112,EHAM,52.30806,4.76417,ZGGG,23.39333,113.30833,2020-06-05 11:35:00+00:00,2020-06-05 21:31:21+00:00,2020-06-05 11:37:00+00:00,2020-06-05 21:34:12+00:00,A388,CSN,B6138,S,Mainline,330.0,4994
38025,239728157,LPBJ,38.07889,-7.93250,ZBTJ,39.12333,117.34500,2020-06-09 15:00:00+00:00,2020-06-10 02:08:03+00:00,2020-06-09 15:33:00+00:00,2020-06-10 02:43:47+00:00,A388,ZZZ,9HMIP,N,Charter,380.0,5327
39683,239730253,ZGGG,23.39333,113.30833,EGLL,51.47750,-0.46139,2020-06-10 01:30:00+00:00,2020-06-10 13:14:06+00:00,2020-06-10 01:30:00+00:00,2020-06-10 13:27:02+00:00,A388,CSN,B6138,S,Mainline,380.0,5174
43443,239735792,ZGGG,23.39333,113.30833,EHAM,52.30806,4.76417,2020-06-10 16:05:00+00:00,2020-06-11 03:25:13+00:00,2020-06-10 16:07:00+00:00,2020-06-11 03:45:07+00:00,A388,CSN,B6140,S,Mainline,361.0,5043
49584,239744147,EGLL,51.47750,-0.46139,ZGGG,23.39333,113.30833,2020-06-11 21:35:00+00:00,2020-06-12 08:26:29+00:00,2020-06-11 21:42:00+00:00,2020-06-12 08:22:03+00:00,A388,CSN,B6138,S,Mainline,350.0,5217
52430,239748249,EHAM,52.30806,4.76417,ZGGG,23.39333,113.30833,2020-06-12 11:35:00+00:00,2020-06-12 21:55:30+00:00,2020-06-12 11:41:00+00:00,2020-06-12 22:01:09+00:00,A388,CSN,B6140,S,Mainline,350.0,5028
60488,239758579,CYUL,45.46806,-73.74139,ZBTJ,39.12333,117.34500,2020-06-14 11:00:00+00:00,2020-06-14 23:30:49+00:00,2020-06-14 10:45:53+00:00,2020-06-14 23:14:20+00:00,A388,ZZZ,9HMIP,N,Charter,330.0,6161
74691,239777681,ZGGG,23.39333,113.30833,EGLL,51.47750,-0.46139,2020-06-17 01:30:00+00:00,2020-06-17 13:00:54+00:00,2020-06-17 01:32:00+00:00,2020-06-17 13:24:14+00:00,A388,CSN,B6140,S,Mainline,380.0,5206
79078,239784138,ZGGG,23.39333,113.30833,EHAM,52.30806,4.76417,2020-06-17 16:05:00+00:00,2020-06-18 03:17:27+00:00,2020-06-17 16:11:00+00:00,2020-06-18 03:43:28+00:00,A388,CSN,B6137,S,Mainline,381.0,5051
86551,239794055,EGLL,51.47750,-0.46139,ZGGG,23.39333,113.30833,2020-06-18 21:35:00+00:00,2020-06-19 08:37:09+00:00,2020-06-18 21:32:00+00:00,2020-06-19 08:32:01+00:00,A388,CSN,B6140,S,Mainline,350.0,5233
89831,239798642,EHAM,52.30806,4.76417,ZGGG,23.39333,113.30833,2020-06-19 11:35:00+00:00,2020-06-19 21:53:06+00:00,2020-06-19 11:52:00+00:00,2020-06-19 22:16:41+00:00,A388,CSN,B6137,S,Mainline,330.0,5045
103847,239816244,CYUL,45.46806,-73.74139,LPBJ,38.07889,-7.93250,2020-06-22 02:30:00+00:00,2020-06-22 08:47:33+00:00,2020-06-22 02:49:00+00:00,2020-06-22 09:06:00+00:00,A388,ZZZ,9HMIP,N,Charter,410.0,2925
116951,239833894,ZGGG,23.39333,113.30833,EGLL,51.47750,-0.46139,2020-06-24 01:30:00+00:00,2020-06-24 12:54:25+00:00,2020-06-24 01:35:00+00:00,2020-06-24 13:25:58+00:00,A388,CSN,B6137,S,Mainline,361.0,5245
122003,239841007,ZGGG,23.39333,113.30833,EHAM,52.30806,4.76417,2020-06-24 16:05:00+00:00,2020-06-25 03:04:36+00:00,2020-06-24 16:07:00+00:00,2020-06-25 03:17:42+00:00,A388,CSN,B6136,S,Mainline,361.0,5044
130398,239852376,EGLL,51.47750,-0.46139,ZGGG,23.39333,113.30833,2020-06-25 21:35:00+00:00,2020-06-26 08:11:50+00:00,2020-06-25 21:23:00+00:00,2020-06-26 08:15:26+00:00,A388,CSN,B6137,S,Mainline,350.0,5183
134295,239857635,EHAM,52.30806,4.76417,ZGGG,23.39333,113.30833,2020-06-26 11:35:00+00:00,2020-06-26 22:05:47+00:00,2020-06-26 11:38:00+00:00,2020-06-26 22:08:49+00:00,A388,CSN,B6136,S,Mainline,330.0,5034
155191,239884629,EGLL,51.47750,-0.46139,ZHCC,34.51833,113.84000,2020-06-29 15:20:00+00:00,2020-06-30 00:44:19+00:00,2020-06-29 15:57:00+00:00,2020-06-30 01:21:58+00:00,A388,CSN,B6140,N,Charter,350.0,4632

### Query all flights from June 15th (1pt)

In [9]:
flights[['aobt', 'fobt']].describe().reset_index()

C:\Users\ahmad.alashmony\AppData\Local\Temp\ipykernel_30968\4142591128.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  flights[['aobt', 'fobt']].describe().reset_index()
C:\Users\ahmad.alashmony\AppData\Local\Temp\ipykernel_30968\4142591128.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  flights[['aobt', 'fobt']].describe().reset_index()

    index                       aobt                       fobt
0   count                     164166                     164166
1  unique                      54451                      11908
2     top  2020-06-22 04:58:00+00:00  2020-06-26 14:00:00+00:00
3    freq                         21                        114
4   first  2020-05-31 23:05:00+00:00  2020-06-01 00:00:00+00:00
5    last  2020-07-01 00:13:00+00:00  2020-06-30 23:58:00+00:00

In [10]:
#All flights in the dataframe flied within June, A: is the Actual and will run the query on the actual flight date
flights.query('aobt.dt.day == 15')

,id,origin,lat_orig,lon_orig,destination,lat_dest,lon_dest,fobt,fat,aobt,aat,actype,operator,reg,flighttype,market,requestfl,distance
62976,239761604,KMEM,35.05000,-89.98333,LFPG,49.00972,2.54778,2020-06-14 23:08:00+00:00,2020-06-15 07:35:43+00:00,2020-06-15 00:27:00+00:00,2020-06-15 09:07:53+00:00,B77L,FDX,N842FD,S,All-Cargo,360.0,4044
63000,239761629,KMEM,35.05000,-89.98333,LFPG,49.00972,2.54778,2020-06-14 23:30:00+00:00,2020-06-15 07:57:51+00:00,2020-06-15 02:27:00+00:00,2020-06-15 11:03:29+00:00,B77L,FDX,N896FD,S,All-Cargo,360.0,4040
63005,239761635,UDYZ,40.14722,44.39583,UMMS,53.88250,28.03083,2020-06-14 23:35:00+00:00,2020-06-15 02:35:55+00:00,2020-06-15 00:11:23+00:00,2020-06-15 03:08:00+00:00,B733,BRU,EW366PA,S,Mainline,340.0,1177
63019,239761650,KMEM,35.05000,-89.98333,LFPG,49.00972,2.54778,2020-06-14 23:45:00+00:00,2020-06-15 08:14:17+00:00,2020-06-15 00:16:00+00:00,2020-06-15 08:50:13+00:00,MD11,FDX,N643FE,S,All-Cargo,370.0,4039
63026,239761658,EDDP,51.42389,12.23639,LGAV,37.93667,23.94444,2020-06-14 23:50:00+00:00,2020-06-15 02:43:58+00:00,2020-06-15 00:00:00+00:00,2020-06-15 02:44:28+00:00,B734,BCS,HAFAZ,S,All-Cargo,310.0,980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68934,239769774,EDDK,50.86583,7.14278,EKCH,55.61806,12.65611,2020-06-16 00:10:00+00:00,2020-06-16 01:36:33+00:00,2020-06-15 23:55:00+00:00,2020-06-16 01:14:27+00:00,B734,BCS,TFBBK,S,All-Cargo,370.0,362
68937,239769783,LTFM,41.27528,28.75194,UCFM,43.06139,74.47750,2020-06-16 00:10:00+00:00,2020-06-16 04:58:03+00:00,2020-06-15 23:57:00+00:00,2020-06-16 04:46:00+00:00,B77W,THY,TCJJY,S,All-Cargo,350.0,2152
68941,239769790,KJFK,40.64028,-73.77833,EGLL,51.47750,-0.46139,2020-06-16 00:15:00+00:00,2020-06-16 07:15:09+00:00,2020-06-15 23:45:00+00:00,2020-06-16 06:34:54+00:00,B772,BAW,GYMML,S,Mainline,390.0,3048
68945,239769793,KORD,41.98000,-87.90500,LFPG,49.00972,2.54778,2020-06-16 00:20:00+00:00,2020-06-16 08:19:40+00:00,2020-06-15 23:55:00+00:00,2020-06-16 07:57:19+00:00,B789,AFR,FHRBF,S,Mainline,370.0,3750
68950,239769748,KJFK,40.64028,-73.77833,EGLL,51.47750,-0.46139,2020-06-16 00:30:00+00:00,2020-06-16 07:36:21+00:00,2020-06-15 23:56:00+00:00,2020-06-16 06:53:31+00:00,B772,BAW,GYMMN,S,Mainline,390.0,3042

In [11]:
# Running same query on the filed date
flights.query("fobt.dt.day == 15")

,id,origin,lat_orig,lon_orig,destination,lat_dest,lon_dest,fobt,fat,aobt,aat,actype,operator,reg,flighttype,market,requestfl,distance
63036,239761736,KEWR,40.69667,-74.16833,LLBG,32.00944,34.88556,2020-06-15 00:00:00+00:00,2020-06-15 10:03:52+00:00,2020-06-14 23:49:00+00:00,2020-06-15 09:57:19+00:00,B78X,UAL,N14001,S,Mainline,350.0,5079
63037,239761737,KORD,41.98000,-87.90500,EDDF,50.03333,8.57056,2020-06-15 00:00:00+00:00,2020-06-15 08:19:41+00:00,2020-06-14 23:45:00+00:00,2020-06-15 08:00:24+00:00,B78X,UAL,N91007,N,Charter,390.0,3943
63038,239761741,KATL,33.63333,-84.43333,EGLL,51.47750,-0.46139,2020-06-15 00:01:00+00:00,2020-06-15 07:23:09+00:00,2020-06-14 23:49:00+00:00,2020-06-15 07:18:57+00:00,B789,VIR,GVYUM,S,Mainline,390.0,3695
63039,239761745,CYMX,45.68333,-74.03333,EDDP,51.42389,12.23639,2020-06-15 00:01:00+00:00,2020-06-15 08:03:25+00:00,2020-06-14 23:52:00+00:00,2020-06-15 07:31:09+00:00,A124,ADB,UR82073,N,All-Cargo,330.0,3334
63040,239761749,EBLG,50.63639,5.44278,LEBL,41.29694,2.07833,2020-06-15 00:01:00+00:00,2020-06-15 01:59:51+00:00,2020-06-14 23:45:00+00:00,2020-06-15 01:38:29+00:00,B734,TAY,OOTNP,S,All-Cargo,230.0,645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68912,239769637,LUKK,46.92778,28.93083,UKBB,50.34472,30.89333,2020-06-15 23:55:00+00:00,2020-06-16 01:01:04+00:00,2020-06-15 23:33:00+00:00,2020-06-16 00:25:00+00:00,E190,AUI,UREMA,N,Charter,290.0,225
68913,239769638,GCTS,28.04444,-16.57250,LEMG,36.67500,-4.49917,2020-06-15 23:55:00+00:00,2020-06-16 02:02:38+00:00,2020-06-15 23:53:00+00:00,2020-06-16 01:52:27+00:00,B738,AEA,ECMKL,N,Charter,400.0,823
68914,239769640,EGSS,51.88500,0.23500,EGPH,55.95000,-3.37250,2020-06-15 23:55:00+00:00,2020-06-16 01:00:10+00:00,2020-06-15 23:56:00+00:00,2020-06-16 00:52:18+00:00,B734,NPT,GNPTX,S,All-Cargo,340.0,293
68915,239769641,LTBA,40.97611,28.81417,UAAA,43.35556,77.04389,2020-06-15 23:55:00+00:00,2020-06-16 05:00:04+00:00,2020-06-16 00:08:00+00:00,2020-06-16 05:08:35+00:00,A332,ZZZ,BLNZ,S,All-Cargo,350.0,2289
68916,239769643,HAAB,8.98333,38.80000,EIDW,53.42139,-6.27000,2020-06-15 23:59:00+00:00,2020-06-16 07:39:24+00:00,2020-06-15 23:48:15+00:00,2020-06-16 07:22:50+00:00,B789,ETH,ETAUO,S,Mainline,380.0,3574

In [12]:
# Running same query from 15 forward
display(flights.query('aobt.dt.day >= 15'), flights.query('fobt.dt.day >= 15'))

,id,origin,lat_orig,lon_orig,destination,lat_dest,lon_dest,fobt,fat,aobt,aat,actype,operator,reg,flighttype,market,requestfl,distance
3,239675739,UUDD,55.40861,37.90639,EBLG,50.63639,5.44278,2020-06-01 00:00:00+00:00,2020-06-01 02:45:51+00:00,2020-05-31 23:55:00+00:00,2020-06-01 02:49:07+00:00,B748,ABW,VQBFE,N,All-Cargo,340.0,1246
5,239675741,KORD,41.98000,-87.90500,LFPG,49.00972,2.54778,2020-06-01 00:00:00+00:00,2020-06-01 07:38:14+00:00,2020-05-31 23:55:00+00:00,2020-06-01 07:40:01+00:00,B788,AAL,N802AN,S,Mainline,370.0,3621
6,239675742,EBLG,50.63639,5.44278,LEBL,41.29694,2.07833,2020-06-01 00:01:00+00:00,2020-06-01 01:57:26+00:00,2020-05-31 23:50:00+00:00,2020-06-01 01:41:14+00:00,B734,TAY,OEIAD,S,All-Cargo,230.0,647
8,239675744,EBLG,50.63639,5.44278,LGAV,37.93667,23.94444,2020-06-01 00:05:00+00:00,2020-06-01 03:06:36+00:00,2020-05-31 23:55:00+00:00,2020-06-01 02:46:02+00:00,B738,TAY,OEIMD,S,All-Cargo,350.0,1128
9,239675745,RKSI,37.46250,126.43917,EDDF,50.03333,8.57056,2020-06-01 00:05:00+00:00,2020-06-01 11:13:21+00:00,2020-05-31 23:45:00+00:00,2020-06-01 10:52:58+00:00,B77L,GEC,DALFC,S,All-Cargo,300.0,4809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164161,239892812,OAMS,36.70000,67.10000,EDDK,50.86583,7.14278,2020-06-30 23:55:00+00:00,2020-07-01 06:59:24+00:00,2020-06-30 23:46:38+00:00,2020-07-01 07:00:09+00:00,B763,PVG,ECLZO,N,Charter,320.0,2834
164162,239893933,DAAG,36.69444,3.21694,EDDK,50.86583,7.14278,2020-06-30 23:55:00+00:00,2020-07-01 02:17:30+00:00,2020-06-30 23:40:46+00:00,2020-07-01 02:04:20+00:00,A321,ART,YLLDA,N,Charter,330.0,957
164163,239894479,UKBB,50.34472,30.89333,LTAC,40.12806,32.99500,2020-06-30 23:55:00+00:00,2020-07-01 02:01:58+00:00,2020-06-30 23:50:00+00:00,2020-07-01 01:33:00+00:00,B738,PGT,TCCRA,S,Lowcost,370.0,659
164164,239896814,EGSS,51.88500,0.23500,EGPH,55.95000,-3.37250,2020-06-30 23:55:00+00:00,2020-07-01 01:02:00+00:00,2020-06-30 23:41:00+00:00,2020-07-01 00:46:22+00:00,B734,NPT,GCKUZ,S,All-Cargo,340.0,296
164165,239895061,EDDP,51.42389,12.23639,LTBA,40.97611,28.81417,2020-06-30 23:58:00+00:00,2020-07-01 02:28:04+00:00,2020-06-30 23:54:00+00:00,2020-07-01 02:20:00+00:00,A306,MNB,TCMCD,S,All-Cargo,350.0,975

,id,origin,lat_orig,lon_orig,destination,lat_dest,lon_dest,fobt,fat,aobt,aat,actype,operator,reg,flighttype,market,requestfl,distance
63036,239761736,KEWR,40.69667,-74.16833,LLBG,32.00944,34.88556,2020-06-15 00:00:00+00:00,2020-06-15 10:03:52+00:00,2020-06-14 23:49:00+00:00,2020-06-15 09:57:19+00:00,B78X,UAL,N14001,S,Mainline,350.0,5079
63037,239761737,KORD,41.98000,-87.90500,EDDF,50.03333,8.57056,2020-06-15 00:00:00+00:00,2020-06-15 08:19:41+00:00,2020-06-14 23:45:00+00:00,2020-06-15 08:00:24+00:00,B78X,UAL,N91007,N,Charter,390.0,3943
63038,239761741,KATL,33.63333,-84.43333,EGLL,51.47750,-0.46139,2020-06-15 00:01:00+00:00,2020-06-15 07:23:09+00:00,2020-06-14 23:49:00+00:00,2020-06-15 07:18:57+00:00,B789,VIR,GVYUM,S,Mainline,390.0,3695
63039,239761745,CYMX,45.68333,-74.03333,EDDP,51.42389,12.23639,2020-06-15 00:01:00+00:00,2020-06-15 08:03:25+00:00,2020-06-14 23:52:00+00:00,2020-06-15 07:31:09+00:00,A124,ADB,UR82073,N,All-Cargo,330.0,3334
63040,239761749,EBLG,50.63639,5.44278,LEBL,41.29694,2.07833,2020-06-15 00:01:00+00:00,2020-06-15 01:59:51+00:00,2020-06-14 23:45:00+00:00,2020-06-15 01:38:29+00:00,B734,TAY,OOTNP,S,All-Cargo,230.0,645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164161,239892812,OAMS,36.70000,67.10000,EDDK,50.86583,7.14278,2020-06-30 23:55:00+00:00,2020-07-01 06:59:24+00:00,2020-06-30 23:46:38+00:00,2020-07-01 07:00:09+00:00,B763,PVG,ECLZO,N,Charter,320.0,2834
164162,239893933,DAAG,36.69444,3.21694,EDDK,50.86583,7.14278,2020-06-30 23:55:00+00:00,2020-07-01 02:17:30+00:00,2020-06-30 23:40:46+00:00,2020-07-01 02:04:20+00:00,A321,ART,YLLDA,N,Charter,330.0,957
164163,239894479,UKBB,50.34472,30.89333,LTAC,40.12806,32.99500,2020-06-30 23:55:00+00:00,2020-07-01 02:01:58+00:00,2020-06-30 23:50:00+00:00,2020-07-01 01:33:00+00:00,B738,PGT,TCCRA,S,Lowcost,370.0,659
164164,239896814,EGSS,51.88500,0.23500,EGPH,55.95000,-3.37250,2020-06-30 23:55:00+00:00,2020-07-01 01:02:00+00:00,2020-06-30 23:41:00+00:00,2020-07-01 00:46:22+00:00,B734,NPT,GCKUZ,S,All-Cargo,340.0,296
164165,239895061,EDDP,51.42389,12.23639,LTBA,40.97611,28.81417,2020-06-30 23:58:00+00:00,2020-07-01 02:28:04+00:00,2020-06-30 23:54:00+00:00,2020-07-01 02:20:00+00:00,A306,MNB,TCMCD,S,All-Cargo,350.0,975

In [13]:
# function to calculate great circle distance between two locations
def calc_gcd(r):
    lat1 = np.radians(r.lat_orig)
    lon1 = np.radians(r.lon_orig)
    lat2 = np.radians(r.lat_dest)
    lon2 = np.radians(r.lon_dest)

    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    c = 2 * np.arcsin(np.sqrt(a))
    d = c * 6371 * 0.539957  # nautical miles
    return d

### Query flights from June 15th, and then calculate the great circle distance with apply() (1pt)

In [14]:
flights.query('aobt.dt.day == 15').apply(calc_gcd, axis = 1)

62976    3951.229677
63000    3951.229677
63005    1057.185825
63019    3951.229677
63026     948.994257
            ...
68934     347.117127
68937    2012.270491
68941    2991.023380
68945    3598.357187
68950    2991.023380
Length: 5886, dtype: float64

### With one nest command: (2 pts)
- add a new column named **gcd** (great circle distance) for all the flights
- then add another new column that calculates the different between **distance** and **gcd**, with column name **distance_diff**

In [15]:
flights = flights.assign(gcd = flights.apply(calc_gcd, axis=1)).assign(distance_diff = lambda x: x.distance - x.gcd)

### Show statistics of the new **distance_diff** column (1 pt)

In [16]:
flights['distance_diff'].describe()

count    161895.000000
mean         53.410255
std          80.332448
min          -4.215734
25%          15.650968
50%          32.820048
75%          60.692777
max        3030.000000
Name: distance_diff, dtype: float64

### Use eval() function to add a new column **duration**, which is the total duration of each flight (hint: based on aat and aobt) (1 pt)

In [17]:
#flights.eval("duration = aat - aobt", inplace=True)
#It does not work, let us check data types 

#flights.dtypes

# I will do it in a different way
#flights = flights.eval("duration = aat - aobt")

#Does not work also
#flights.head(1).eval('duration = aat - aobt')

# It seems that we have an issue already on Stackoverflow for substracting this data type https://stackoverflow.com/questions/22052337/unable-to-subtract-datetime64-using-dataframe-eval
# The issue is reported via GitHub also https://github.com/pandas-dev/pandas/issues/5007

flights['duration'] = flights['aat'] = flights['aobt']

### Group by **market**, and show mean, median, and max flight distance of each group (1 pt)

In [18]:
flights.columns

Index(['id', 'origin', 'lat_orig', 'lon_orig', 'destination', 'lat_dest',
       'lon_dest', 'fobt', 'fat', 'aobt', 'aat', 'actype', 'operator', 'reg',
       'flighttype', 'market', 'requestfl', 'distance', 'gcd', 'distance_diff',
       'duration'],
      dtype='object')

In [19]:
flights.groupby('market').agg({'distance': ['mean', 'median', 'max']})

                      distance
                          mean median   max
market
All-Cargo          1512.841581    650  7391
Business Aviation   593.487904    384  6073
Charter            1985.751477   1200  7340
Lowcost             660.526758    589  6104
Mainline           1710.671427    675  8052
Other Types          99.276937    104   462
Regional Aircraft   228.464703    166  1940

### Get the most common 20 aircraft type codes (**actype**) and the number of flights per type (1 pt)

In [20]:
flights.groupby('actype').agg({'id':'count'}).sort_values(by = 'id', ascending=False).reset_index().head(20)

   actype     id
0    B738  17127
1    A320  13605
2    B77W   6382
3    A319   6004
4    B734   5506
5    A20N   5416
6    A321   4778
7    B77L   4597
8     S92   4467
9    DH8D   4167
10   AT75   3677
11   B789   3624
12   DH8A   3621
13   B752   3435
14   E190   3116
15   B744   3087
16   C56X   2994
17   AT76   2928
18   A332   2553
19   B763   2300

### Nesting operations (3 pts)

- Query flights originated from Paris Charles de Gaulle Airport (airport code: LFPG)
- Calculate arrival delays of all airports
- Group by destination
- Calculated the mean flight distance and average arrival delay at the destination airports
- Sow and sort results for destinations with average arrival delay large than 10 minutes with more than 5 flights

In [21]:
flights.columns

Index(['id', 'origin', 'lat_orig', 'lon_orig', 'destination', 'lat_dest',
       'lon_dest', 'fobt', 'fat', 'aobt', 'aat', 'actype', 'operator', 'reg',
       'flighttype', 'market', 'requestfl', 'distance', 'gcd', 'distance_diff',
       'duration'],
      dtype='object')

In [22]:
flights.query('origin == "LFPG"').assign(delay= lambda x : (x.fat-x.aat).dt.total_seconds() / 60).groupby('destination')\
    .agg({'distance': 'mean', 'delay':'mean','id':'count'})\
    .query('delay > 10 and id > 5').sort_values(by='delay', ascending=False).reset_index()

    destination     distance       delay   id
0          WSSS  5895.153846  733.497436   13
1          VVTS  5628.470588  690.036275   17
2          RCTP  5802.266667  686.370000   15
3          RJAA  5441.230769  685.701923   26
4          RJTT  5289.722222  679.315741   18
..          ...          ...         ...  ...
122        EHAM   238.436975   53.751821  119
123        LFLC   220.000000   53.671429    7
124        LFRS   224.166667   51.541667   12
125        EBLG   186.720930   47.920155   43
126        EBBR   177.842105   36.654386   19

[127 rows x 4 columns]

# Visualization

In [23]:
import matplotlib.pyplot as plt
import seaborn as sns

c:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 1.20.1)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

### Create bar plot for the most common 20 aircraft types (1 pts)

### Create bar plot for the most common 20 aircraft types showing variations among operators (group by operators) (2 pts)

### Plot the departure and arrival delay trends over the 24-hours for at Paris Charles de Gaulle Airport (LFPG) airport (2 pts)
- based on all flights departing and arriving at LFPG
- you should consider the variations for different days

### Using boxplot() to plot the arrival and departure delay statistics for each of the top 15 airport (1 pts)
 - remark: top airports according to number of total departures

### Plot the same result from previous visualization in violinplot() (1 pts)
- remember to try different **split**, **palette**, and **inner** arguments

### Use jointplot() to show the relationship between departure and arrival delays with 2D kde plot, you should:  (2 pts)   

 - randomly sample 10000 flights for the plot for better performance
 - limit showing delays between -60 and 60 minutes for better visualization

### Use relplot() to show the arrival and delay trend over 24-hour period for top 15 airports (2 pts)
- you should considering the variation during different days
- you should checkout different **col_wrap** and **kind** arguments